// Colors
export const THEME = {
    BACKGROUND_COLOR: '#FFFFFF',
    SECONDARY_BACKGROUND_COLOR: '#EBEEF2',

    ACCENT_COLOR: '#1F1F1F',
    CONTRAST_COLOR: '#000000',

    TEXT_COLOR: '#000000',
    SECONDARY_TEXT_COLOR: '#C6C6C6',

    GREEN_COLOR: '#68BF79',
}