export const REPORTS_GET_ALL_DATA_LOADING = 'REPORTS_GET_ALL_DATA_LOADING';
export const REPORTS_GET_ALL_DATA_LOADED = 'REPORTS_GET_ALL_DATA_LOADED';
export const REPORTS_GET_ALL_DATA_FAIL = 'REPORTS_GET_ALL_DATA_FAIL';