export const APP_STATE_LOADING = 'APP_STATE_LOADING';
export const APP_STATE_LOADED = 'APP_STATE_LOADED';
export const APP_STATE_FAIL = 'APP_STATE_FAIL';

export const REPORTS_GET_ALL_DATA_LOADING = 'REPORTS_GET_ALL_DATA_LOADING';
export const REPORTS_GET_ALL_DATA_LOADED = 'REPORTS_GET_ALL_DATA_LOADED';
export const REPORTS_GET_ALL_DATA_FAIL = 'REPORTS_GET_ALL_DATA_FAIL';

export const REPORTS_GET_BY_MONTH_LOADING = 'REPORTS_GET_BY_MONTH_LOADING';
export const REPORTS_GET_BY_MONTH_LOADED = 'REPORTS_GET_BY_MONTH_LOADED';
export const REPORTS_GET_BY_MONTH_FAIL = 'REPORTS_GET_BY_MONTH_FAIL';

export const REPORTS_CREATE_LOADING = 'REPORTS_CREATE_LOADING';
export const REPORTS_CREATE_LOADED = 'REPORT_CREATE_LOADED';
export const REPORTS_CREATE_FAIL = 'REPORTS_CREATE_FAIL';

export const REPORTS_EDIT_LOADING = 'REPORTS_EDIT_LOADING';
export const REPORTS_EDIT_LOADED = 'REPORTS_EDIT_LOADED';
export const REPORTS_EDIT_FAIl = 'REPORTS_EDIT_FAIl';

export const REPORTS_DELETE_LOADING = 'REPORTS_DELETE_LOADING';
export const REPORTS_DELETE_LOADED = 'REPORTS_DELETE_LOADED';
export const REPORTS_DELETE_FAIL = 'REPORTS_DELETE_FAIL';

export const REPORTS_GET_MIN_YEAR_LOADING = 'REPORTS_GET_MIN_YEAR_LOADING';
export const REPORTS_GET_MIN_YEAR_LOADED = 'REPORTS_GET_MIN_YEAR_LOADED';
export const REPORTS_GET_MIN_YEAR_FAIL = 'REPORTS_GET_MIN_YEAR_FAIL';

export const REPORST_GET_STATS_BY_YEAR_LOADING = 'REPORST_GET_STATS_BY_YEAR_LOADING';
export const REPORST_GET_STATS_BY_YEAR_LOADED = 'REPORST_GET_STATS_BY_YEAR_LOADED';
export const REPORST_GET_STATS_BY_YEAR_FAIL = 'REPORST_GET_STATS_BY_YEAR_FAIL';

export const ACTIVE_REPORT_LOADING = 'ACTIVE_REPORT_LOADING';
export const ACTIVE_REPORT_LOADED = 'ACTIVE_REPORT_LOADED';
export const ACTIVE_REPORT_FAIL = 'ACTIVE_REPORT_FAIL';
