export const REPORTS_GET_ALL_DATA_LOADING = 'REPORTS_GET_ALL_DATA_LOADING';
export const REPORTS_GET_ALL_DATA_LOADED = 'REPORTS_GET_ALL_DATA_LOADED';
export const REPORTS_GET_ALL_DATA_FAIL = 'REPORTS_GET_ALL_DATA_FAIL';

export const REPORTS_GET_BY_MONTH_LOADING = 'REPORTS_GET_BY_MONTH_LOADING';
export const REPORTS_GET_BY_MONTH_LOADED = 'REPORTS_GET_BY_MONTH_LOADED';
export const REPORTS_GET_BY_MONTH_FAIL = 'REPORTS_GET_BY_MONTH_FAIL';

export const REPORTS_CREATE_LOADING = 'REPORTS_CREATE_LOADING';
export const REPORTS_CREATE_LOADED = 'REPORT_CREATE_LOADED';
export const REPORTS_CREATE_FAIL = 'REPORTS_CREATE_FAIL';

export const REPORTS_GET_MIN_YEAR_LOADING = 'REPORTS_GET_MIN_YEAR_LOADING';
export const REPORTS_GET_MIN_YEAR_LOADED = 'REPORTS_GET_MIN_YEAR_LOADED';
export const REPORTS_GET_MIN_YEAR_FAIL = 'REPORTS_GET_MIN_YEAR_FAIL';
